[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd client && npm install --include=dev",
  "cd server && npm install --include=dev"
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && node index.js"
